### ISSUE TITLE
standard errors bootstrap with RVAR

### ISSUE THREAD

**Issue by ninowski** [tylerJPike/sovereign#5]
Hi,
I am writing to ask you about the package you developed on R (sovereign). 
Specifically, I wanted to ask about the differences between your package and tsDyn, with which it is possible to estimate TVAR with an external threshold. 

The TVAR command with an external threshold does not allow standard errors to be calculated with bootstrap, whereas the RVAR package does. 
Furthermore, in the TVAR package, it is possible to calculate GIRFs, as Koop et al. (1996) proposed. 
What is the difference between GIRFs and IRFs estimated with RVAR?

Thank you in advance for your help

**Comment by tylerJPike** [comment]
Thank you for your patience in waiting for my reply - it sounds like you will be able to sympathize with the time demands of grad school. 

From my reading of Koop et al. (1996) and the TsDyn manual, the GIRF is more flexible than the traditional bootstrapped IRF. RVAR constructs synthetic times of the endogenous variables from reshuffling and/or scaling residuals. In this process, RVAR does not allow one to control the observations or innovations used in the bootstrapping (outside its use of exogenous regimes to partition the observations). This appears to be the key difference between  sovereign IRFs and the TsDyn GIRFs. Therefore, if you need to control the histories or innovations used in constructing IRFS, say if you were interested in responses to very large innovations, then  GIRFs may be the more useful tool. That is, RVAR can condition on observable states of the world, but not endogenously estimated innovations.
