### ISSUE TITLE
Instrument Relevance Tests

### ISSUE THREAD

**Issue by muhsinciftci** [tylerJPike/sovereign#6]
How can One get the statistics for instrument relevance? (F-stats etc?)

**Comment by tylerJPike** [comment]
The statistic, namely the F-test, should be reported (by default) when one runs the "IV" or "IV-short" identification routine in the VAR function. If this is not the case for you, then please post code to reproduce the problem.

**Comment by muhsinciftci** [comment]
Thanks. A bit hard to notice at first glance. A heteroskedasticity robust F-stat would be nice to include.
