### ISSUE TITLE
IV Estimation not Working?

### ISSUE THREAD

**Issue by julianmarenz** [tylerJPike/sovereign#7]
Hi, thanks for the effot in creating this package. I tried to estimate a VAR using an instrument. However, coefficient estimates are exactly the same, whether I include the instrument or run a standard VAR. Checking the source code I have noticed that in the ``VAR_estimation.R`` function, ``instrument`` is a possible input but it does not seem to appear anywhere inside the function.

Potentially I am missing something - but, as of now, does the external instrument identification work? Thanks!

**Comment by tylerJPike** [comment]
The IV estimation is implemented for identifying shocks via an external instrument, as in Gertler and Karadi (2015). As such, the elements of the coefficient matrix will not change when using the IV identification option, but rather, the elements of the impact matrix will. The IV implementation can be seen in `solve_V.R`, starting on line 50.
